#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xrdb ~/.Xresources &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh &
feh --bg-scale ~/.config/bspwm/wallpaper/wallpaper.jpg &
dunst &

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width 		      0
bspc config border_radius		      10
bspc config window_gap			      14
bspc config split_ration			    0.50
bspc config borderless_monocle  	true
bspc config gapless_monocle		    true
bspc config focus_follows_pointer	true
bspc config pointer_modifier 		  mod1

bspc rule -a "Lxappearance" state=floating
bspc rule -a "Pcmanfm" state=floating
bspc rule -a "Sxiv" state=floating

